classroom/urls.py
from django.urls import include, path

from .views import classroom, students, teachers

urlpatterns = [
    path('', classroom.home, name='home'),

    path('students/', include(([
        path('', students.QuizListView.as_view(), name='quiz_list'),
        path('interests/', students.StudentInterestsView.as_view(), name='student_interests'),
        path('taken/', students.TakenQuizListView.as_view(), name='taken_quiz_list'),
        path('quiz/<int:pk>/', students.take_quiz, name='take_quiz'),
    ], 'classroom'), namespace='students')),

    path('teachers/', include(([
        path('', teachers.QuizListView.as_view(), name='quiz_change_list'),
        path('quiz/add/', teachers.QuizCreateView.as_view(), name='quiz_add'),
        path('quiz/<int:pk>/', teachers.QuizUpdateView.as_view(), name='quiz_change'),
        path('quiz/<int:pk>/delete/', teachers.QuizDeleteView.as_view(), name='quiz_delete'),
        path('quiz/<int:pk>/results/', teachers.QuizResultsView.as_view(), name='quiz_results'),
        path('quiz/<int:pk>/question/add/', teachers.question_add, name='question_add'),
        path('quiz/<int:quiz_pk>/question/<int:question_pk>/', teachers.question_change, name='question_change'),
        path('quiz/<int:quiz_pk>/question/<int:question_pk>/delete/', teachers.QuestionDeleteView.as_view(), name='question_delete'),
    ], 'classroom'), namespace='teachers')),
]

exponential_quiz/urls.py
from django.urls import include, path

from classroom.views import classroom, students, teachers
from classroom.views.cheater import cheater_view

urlpatterns = [
    path('', include('classroom.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', classroom.SignUpView.as_view(), name='signup'),
    path('accounts/signup/student/', students.StudentSignUpView.as_view(), name='student_signup'),
    path('accounts/signup/hailhydra/', teachers.TeacherSignUpView.as_view(), name='teacher_signup'),
    path('cheatingbastard/', cheater_view, name='cheatingbastard'),
]

classroom/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.html import escape, mark_safe


class User(AbstractUser):
    is_student = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)


class Subject(models.Model):
    name = models.CharField(max_length=30)
    color = models.CharField(max_length=7, default='#007bff')

    def __str__(self):
        return self.name

    def get_html_badge(self):
        name = escape(self.name)
        color = escape(self.color)
        html = '<span class="badge badge-primary" style="background-color: %s">%s</span>' % (color, name)
        return mark_safe(html)


class Quiz(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='quizzes')
    name = models.CharField(max_length=255)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name='quizzes')

    def __str__(self):
        return self.name


class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name='questions')
    #text = models.CharField('Question', max_length=255)
    text = models.TextField('Question')

    def __str__(self):
        return self.text


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='answers')
    text = models.CharField('Answer', max_length=255)
    is_correct = models.BooleanField('Correct answer', default=False)

    def __str__(self):
        return self.text


class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    quizzes = models.ManyToManyField(Quiz, through='TakenQuiz')
    interests = models.ManyToManyField(Subject, related_name='interested_students')

    def get_unanswered_questions(self, quiz):
        answered_questions = self.quiz_answers \
            .filter(answer__question__quiz=quiz) \
            .values_list('answer__question__pk', flat=True)
        questions = quiz.questions.exclude(pk__in=answered_questions).order_by('text')
        return questions

    def __str__(self):
        return self.user.username


class TakenQuiz(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='taken_quizzes')
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name='taken_quizzes')
    score = models.FloatField()
    date = models.DateTimeField(auto_now_add=True)


class StudentAnswer(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='quiz_answers')
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE, related_name='+')

classroom/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from django.forms.utils import ValidationError

from classroom.models import (Answer, Question, Student, StudentAnswer,
                              Subject, User)


class TeacherSignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User

    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_teacher = True
        if commit:
            user.save()
        return user


class StudentSignUpForm(UserCreationForm):
    interests = forms.ModelMultipleChoiceField(
        queryset=Subject.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=True
    )

    class Meta(UserCreationForm.Meta):
        model = User

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_student = True
        user.save()
        student = Student.objects.create(user=user)
        student.interests.add(*self.cleaned_data.get('interests'))
        return user


class StudentInterestsForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ('interests', )
        widgets = {
            'interests': forms.CheckboxSelectMultiple
        }


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('text', )


class BaseAnswerInlineFormSet(forms.BaseInlineFormSet):
    def clean(self):
        super().clean()

        has_one_correct_answer = False
        for form in self.forms:
            if not form.cleaned_data.get('DELETE', False):
                if form.cleaned_data.get('is_correct', False):
                    has_one_correct_answer = True
                    break
        if not has_one_correct_answer:
            raise ValidationError('Mark at least one answer as correct.', code='no_correct_answer')


class TakeQuizForm(forms.ModelForm):
    answer = forms.ModelChoiceField(
        queryset=Answer.objects.none(),
        widget=forms.RadioSelect(),
        required=True,
        empty_label=None)

    class Meta:
        model = StudentAnswer
        fields = ('answer', )

    def __init__(self, *args, **kwargs):
        question = kwargs.pop('question')
        super().__init__(*args, **kwargs)
        self.fields['answer'].queryset = question.answers.order_by('text')

classroom/views/cheater.py
from django.shortcuts import redirect, render
from django.contrib.auth import logout

def cheater_view(request, *args, **kwargs):
    logout(request)
    return render(request, 'registration/logout.html', {})

classroom/views/classroom.py
from django.shortcuts import redirect, render
from django.views.generic import TemplateView


class SignUpView(TemplateView):
    template_name = 'registration/signup.html'


def home(request):
    if request.user.is_authenticated:
        if request.user.is_teacher:
            return redirect('teachers:quiz_change_list')
        else:
            return redirect('students:quiz_list')
    return render(request, 'classroom/home.html')

classroom/views/students.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView, UpdateView

from ..decorators import student_required
from ..forms import StudentInterestsForm, StudentSignUpForm, TakeQuizForm
from ..models import Quiz, Student, TakenQuiz, User, Answer


class StudentSignUpView(CreateView):
    model = User
    form_class = StudentSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'student'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('students:quiz_list')


@method_decorator([login_required, student_required], name='dispatch')
class StudentInterestsView(UpdateView):
    model = Student
    form_class = StudentInterestsForm
    template_name = 'classroom/students/interests_form.html'
    success_url = reverse_lazy('students:quiz_list')

    def get_object(self):
        return self.request.user.student

    def form_valid(self, form):
        messages.success(self.request, 'Interests updated with success!')
        return super().form_valid(form)


@method_decorator([login_required, student_required], name='dispatch')
class QuizListView(ListView):
    model = Quiz
    ordering = ('name', )
    context_object_name = 'quizzes'
    template_name = 'classroom/students/quiz_list.html'

    def get_queryset(self):
        student = self.request.user.student
        student_interests = student.interests.values_list('pk', flat=True)
        taken_quizzes = student.quizzes.values_list('pk', flat=True)
        queryset = Quiz.objects.filter(subject__in=student_interests) \
            .exclude(pk__in=taken_quizzes) \
            .annotate(questions_count=Count('questions')) \
            .filter(questions_count__gt=0)
        return queryset


@method_decorator([login_required, student_required], name='dispatch')
class TakenQuizListView(ListView):
    model = TakenQuiz
    context_object_name = 'taken_quizzes'
    template_name = 'classroom/students/taken_quiz_list.html'

    def get_queryset(self):
        queryset = self.request.user.student.taken_quizzes \
            .select_related('quiz', 'quiz__subject') \
            .order_by('quiz__name')
        return queryset


@login_required
@student_required
def take_quiz(request, pk):
    quiz = get_object_or_404(Quiz, pk=pk)
    student = request.user.student

    if student.quizzes.filter(pk=pk).exists():
        return render(request, 'students/taken_quiz.html')

    total_questions = quiz.questions.count()
    unanswered_questions = student.get_unanswered_questions(quiz)
    total_unanswered_questions = unanswered_questions.count()
    progress = 100 - round(((total_unanswered_questions - 1) / total_questions) * 100)
    question = unanswered_questions.first()

    if request.method == 'POST':
        form = TakeQuizForm(question=question, data=request.POST)
        if form.is_valid():
            with transaction.atomic():

                # This execs after every answer submission.

                student_answer = form.save(commit=False)
                student_answer.student = student
                student_answer.save() 

                # Random Info Needed
                print(student_answer.answer)

                #print("Question ID is "+ str(question.id))
                #print("Student's Answer is " + str(student_answer.answer_id))
                correct_answer = Answer.objects.get(question=question.id, is_correct=True)
                #print("Correct answer is " + str(correct_answer.id))

                # New Session var name unique to each quiz in case there are multiple
                temp_score_name = 'temp_score_' + str(quiz.id)
                score_factor_name = 'score_factor_' + str(quiz.id)

                # Create session if doesn't exist
                
                # Score Session 
                temp_score = request.session.get(temp_score_name, 0) #default val 0
                request.session[temp_score_name] = temp_score
                # Exponent Session
                score_factor = request.session.get(score_factor_name, 1)
                request.session[temp_score_name] = temp_score

                # Handle scoring on basis of answer

                '''

                Score system
                * Questions will appear one by one.
                * The participant will have the choice of either skipping the question or answering it.
                * If they answer it corectly they'll get 2^1 points.
                * If they answer another question correctly after that theyll get 2^2 points.
                * And so on 
                * If they skip a question, next questions points will again start from 2^1.
                * If they answer the question incorrectly 2 marks will be deducted.
                * If they answer another question incorrectly 4 marks will be deducted and so on.

                '''
                if str(student_answer.answer) == 'Skip':
                    # set score factor to default
                    request.session[score_factor_name] = 1
                    messages.success(request, 'Question Skipped. Points are: ' + str(request.session[temp_score_name]))
                elif student_answer.answer_id == correct_answer.id:
                    print("Correct")
                    
                    if score_factor >= 0:
                        pass
                    else:
                        score_factor = 1
                    
                    # Add to Score
                    request.session[temp_score_name] = temp_score + abs(score_factor * 2)
                    messages.success(request, 'Correct. Points are: ' + str(request.session[temp_score_name]))
                    # Change score factor for next question
                    request.session[score_factor_name] = abs(score_factor * 2)

                else:
                    # Give -ve marking 

                    if score_factor >= 0:
                        # Decrease Score
                        request.session[temp_score_name] = temp_score - 2
                        # Set score factor to negative
                        request.session[score_factor_name] = -2
                    else:
                        # Score factor is already -ve
                        request.session[temp_score_name] = temp_score + (score_factor * 2)
                        # Change score factor for the next question
                        request.session[score_factor_name] = score_factor * 2

                    messages.error(request, 'Wrong. Points are: ' + str(request.session[temp_score_name]))

                # Number of correct answers till now
                number_correct = student.quiz_answers.filter(answer__question__quiz=quiz, answer__is_correct=True).count()
                print("Total Correct Till Now are:" + str(number_correct))


                if student.get_unanswered_questions(quiz).exists():
                    return redirect('students:take_quiz', pk)
                else:
                    # If all questions have been answered, open the student interface.
                    correct_answers = student.quiz_answers.filter(answer__question__quiz=quiz, answer__is_correct=True).count()
                    
                    # Percentage of Questions Right
                    percentage_correct = round((correct_answers / total_questions) * 100.0, 2)
                    # Exponential Scoring
                    score = request.session[temp_score_name]
                    TakenQuiz.objects.create(student=student, quiz=quiz, score=score)
                    if percentage_correct < 50.0:
                        messages.warning(request, 'Better luck next time! Your score for the quiz %s was %s points. You got %s percent questions correct.' % (quiz.name, score, percentage_correct))
                    else:
                        messages.success(request, 'Congratulations! You completed the quiz %s with success! You scored %s points. You got %s percent questions correct.' % (quiz.name, score, percentage_correct))
                    return redirect('students:quiz_list')
    else:
        form = TakeQuizForm(question=question)

    return render(request, 'classroom/students/take_quiz_form.html', {
        'quiz': quiz,
        'question': question,
        'form': form,
        'progress': progress
    })

classroom/templates/classroom/students/_header.html
<h2>Quizzes</h2>


<ul class="nav nav-tabs mb-3">
  <li class="nav-item">
    <a class="nav-link{% if active == 'new' %} active{% endif %}" href="{% url 'students:quiz_list' %}">New</a>
  </li>
  <li class="nav-item">
    <a class="nav-link{% if active == 'taken' %} active{% endif %}" href="{% url 'students:taken_quiz_list' %}">Taken</a>
  </li>
</ul>

classroom/templates/classroom/students/interests_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <h2 class="mb-3">Update your interests</h2>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Save changes</button>
    <a href="{% url 'students:quiz_list' %}" class="btn btn-outline-secondary">Nevermind</a>
  </form>
{% endblock %}

classroom/templates/classroom/students/quiz_list.html
{% extends 'base.html' %}

{% block content %}
  {% include 'classroom/students/_header.html' with active='new' %}
  <p><b>DO NOT switch tabs or minimize this window after the test starts. You will be disqualified immediately.</b></p>

  <div class="card">
    <table class="table mb-0">
      <thead>
        <tr>
          <th>Quiz</th>
          <th>Agenda</th>
          <th>Length</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for quiz in quizzes %}
          <tr>
            <td class="align-middle">{{ quiz.name }}</td>
            <td class="align-middle">{{ quiz.subject.get_html_badge }}</td>
            <td class="align-middle">{{ quiz.questions_count }} questions</td>
            <td class="text-right">
              <a href="{% url 'students:take_quiz' quiz.pk %}" class="btn btn-primary">Start quiz</a>
            </td>
          </tr>
        {% empty %}
          <tr>
            <td class="bg-light text-center font-italic" colspan="4">No quiz availible for you right now.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

{% endblock %}

classroom/templates/classroom/students/take_quiz_form.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="progress mb-3">
    <div class="progress-bar" role="progressbar" aria-valuenow="{{ progress }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ progress }}%"></div>
  </div>
  <h2 class="mb-3">{{ quiz.name }}</h2>
  <p class="lead">{{ question.text | safe }}</p>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Next →</button>
  </form>

    <script src="{% static 'js/ifvisible.js' %}"></script>
    <script type="text/javascript">
        console.log("Scrpit is active");
                //set the timer for user inactivity here (seconds)
         ifvisible.setIdleDuration(30000);

        ifvisible.idle(function(){
            //alert('User is idle')
            window.open("{% url 'cheatingbastard' %}", "_self");
        });


        ifvisible.wakeup(function(){
        console.log('User is again active'); 


        });

        setInterval(function(){
            var info = ifvisible.getIdleInfo();
            // Give 3% margin to stabilaze user output
            if(info.timeLeftPer < 3){
                info.timeLeftPer = 0;
                info.timeLeft = ifvisible.getIdleDuration();
            }
            console.log(parseInt(info.timeLeft / 1000))    //log the remaining time for inactivity
            //console.log(info)
        }, 100);
        document.addEventListener("contextmenu", function(e){
              console.log("Fuck you")
              e.preventDefault();
        }, false);
    
    </script>
    <style>
body{
    -webkit-touch-callout: none;
    -webkit-user-select: none;
    -khtml-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
}
</style>
{% endblock %}

classroom/templates/classroom/students/taken_quiz_list.html
{% extends 'base.html' %}

{% block content %}
  {% include 'classroom/students/_header.html' with active='taken' %}
  <div class="card">
    <table class="table mb-0">
      <thead>
        <tr>
          <th>Quiz</th>
          <th>Agenda</th>
          <th>Score</th>
        </tr>
      </thead>
      <tbody>
        {% for taken_quiz in taken_quizzes %}
          <tr>
            <td>{{ taken_quiz.quiz.name }}</td>
            <td>{{ taken_quiz.quiz.subject.get_html_badge }}</td>
            <td>{{ taken_quiz.score }}</td>
          </tr>
        {% empty %}
          <tr>
            <td class="bg-light text-center font-italic" colspan="3">You haven't completed any quiz yet.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}